// Total 78 cards
const tarotCards = [
  { image: 'assets/0-theFool.jpg', title: 'The Fool', description: 'The fool symbolizes the embrace of new beginnings, the expansion of ones horizons, and the willingness to take risks guided by intuition. In simpler terms, it encourages you to listen to your inner feelings and take a leap of faith', song: '<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/767610067&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/badbunny15" title="Bad-Bunny" target="_blank" style="color: #cccccc; text-decoration: none;">Bad-Bunny</a> · <a href="https://soundcloud.com/badbunny15/bad-bunny-vete" title="Vete" target="_blank" style="color: #cccccc; text-decoration: none;">Vete</a></div>' },
  { image: 'assets/12-death.jpg', title: 'Death', description: 'Death represents transitions and new beginnings, urging us to accept change. In Love & Relationships, the Death card symbolizes the power of transformation for growth and transcendence. Career & Finances readings warn against resistance to change in order to succeed', song: '<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/767610862&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/badbunny15" title="Bad-Bunny" target="_blank" style="color: #cccccc; text-decoration: none;">Bad-Bunny</a> · <a href="https://soundcloud.com/badbunny15/bad-bunny-amorfoda" title="Amorfoda" target="_blank" style="color: #cccccc; text-decoration: none;">Amorfoda</a></div>' },
  { image: 'assets/11-justice.jpg', title: 'Justice', description: 'Justice represents fairness, balance, and truth, and can encourage people to act with integrity and accept responsibility for their choices. It can also symbolize the need for difficult transitions and inner strength when seeking balance and fairness', song: '<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/767610619&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/badbunny15" title="Bad-Bunny" target="_blank" style="color: #cccccc; text-decoration: none;">Bad-Bunny</a> · <a href="https://soundcloud.com/badbunny15/bad-bunny-caro" title="Caro" target="_blank" style="color: #cccccc; text-decoration: none;">Caro</a></div>' },
  { image: 'assets/21-theWorld.jpg', title: 'The World', description: 'The World is a reminder that you have control over the direction of your life, which is why you should use the knowledge you have gained to help you evolve. The caveat is that you have to let go in order to experience the fresh start you are longing for and doing that can be hard', song: '<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/767610355&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/badbunny15" title="Bad-Bunny" target="_blank" style="color: #cccccc; text-decoration: none;">Bad-Bunny</a> · <a href="https://soundcloud.com/badbunny15/bad-bunny-si-estuviesemos" title="Si Estuviésemos Juntos" target="_blank" style="color: #cccccc; text-decoration: none;">Si Estuviésemos Juntos</a></div>' },
  { image: 'assets/theMagician.jfif', title: 'The Magician', description: 'The Magician tarot card represents manifestation, skill, and the power to turn visions into reality; it’s the symbol of creative potential and resourcefulness', song: '<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/635026017&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/zedsdead" title="Zeds Dead" target="_blank" style="color: #cccccc; text-decoration: none;">Zeds Dead</a> · <a href="https://soundcloud.com/zedsdead/zeds-dead-x-droeloe-stars-tonight" title="Zeds Dead X DROELOE - Stars Tonight" target="_blank" style="color: #cccccc; text-decoration: none;">Zeds Dead X DROELOE - Stars Tonight</a></div>' },
  { image: 'assets/Temperance.webp', title: 'Temperance', description: 'Temperance represents balance, harmony, and moderation, emphasizing the need for patience and compromise. It signifies finding a middle ground and integrating opposites', song: '<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/400638954&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/minnesota" title="Minnesota" target="_blank" style="color: #cccccc; text-decoration: none;">Minnesota</a> · <a href="https://soundcloud.com/minnesota/minnesota-hilow-charlesthefirst-remix" title="Minnesota - HiLow (CharlestheFirst Remix)" target="_blank" style="color: #cccccc; text-decoration: none;">Minnesota - HiLow (CharlestheFirst Remix)</a></div>' },
  { image: 'assets/theHangedMan.webp', title: 'The Hanged Man', description: 'The Hanged Man represents self-reflection, gaining new perspectives, letting go of control, sacrifice for greater understanding, and a period of necessary stillness. It symbolizes pause and surrender', song: '<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/363355004&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/bassnectar" title="Bassnectar" target="_blank" style="color: #cccccc; text-decoration: none;">Bassnectar</a> · <a href="https://soundcloud.com/bassnectar/bassnectar-g-jones-chromatek-reflective-part-2" title="Bassnectar &amp; G Jones - Chromatek ◈ [Reflective Part 2]" target="_blank" style="color: #cccccc; text-decoration: none;">Bassnectar &amp; G Jones - Chromatek ◈ [Reflective Part 2]</a></div>' },
  { image: 'assets/2-theHighPriestess.webp', title: 'The High Priestess', description: 'The High Priestess symbolizes intuition, hidden knowledge, and the subconscious; it can also represent the need for reflection', song: 'https://open.spotify.com/track/1VSngtLdJhrlfHkLxTyOXK?si=84_9STWVRZqhGqrxXOgvJw' },
  { image: 'assets/15-theDevil.webp', title: 'The Devil', description: 'The Devil does not symbolize a specific religious or mythical demonic entity, but the darkness we hold within ourselves. Everyone is flawed in some way, and it is important we each address our own weaknesses', song: '<iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/383Xl5QTigwj3QiA3Qc6S7?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>' },
  { image: 'assets/16-theTower.jpg', title: 'The Tower', description: 'The Tower tells us that change is coming whether we are ready for it or not. This could be a personal tragedy, or some other shift that carries serious consequences. The higher you are, the further you have to fall', song: '<iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/1wi4ti9BYUbwoGJ1EBUVtv?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>' },
  { image: 'assets/3-theEmpress.jpg', title: 'The Empress', description: 'The Empress represents fertility, creativity and nurturing. Interpreting the card upright indicates successful prospects in love, career and finances', song: '<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1639721550&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/badbunny15" title="Bad-Bunny" target="_blank" style="color: #cccccc; text-decoration: none;">Bad-Bunny</a> · <a href="https://soundcloud.com/badbunny15/bad-bunny-acho-pr" title="ACHO PR" target="_blank" style="color: #cccccc; text-decoration: none;">ACHO PR</a></div>' },
  { image: 'assets/7-theChariot.jpg', title: 'The Chariot', description: 'The Chariot encourages us to take charge of our lives and conquer challenges through willpower & determination. It symbolizes the need for balance between conflicting forces, confidence & ambition in order to achieve success', song: '<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1639720266&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/badbunny15" title="Bad-Bunny" target="_blank" style="color: #cccccc; text-decoration: none;">Bad-Bunny</a> · <a href="https://soundcloud.com/badbunny15/bad-bunny-no-me-quiero-casar" title="NO ME QUIERO CASAR" target="_blank" style="color: #cccccc; text-decoration: none;">NO ME QUIERO CASAR</a></div>' },
  { image: 'assets/17-theStar.jpg', title: 'The Star', description: 'The Star brings you the healing, steadying message that you are still you. Whatever has changed, whatever you have been through, that essence of you remains, strong and bright, burning within', song: '<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/768349996&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/badbunny15" title="Bad-Bunny" target="_blank" style="color: #cccccc; text-decoration: none;">Bad-Bunny</a> · <a href="https://soundcloud.com/badbunny15/bad-bunny-solia" title="Soliá" target="_blank" style="color: #cccccc; text-decoration: none;">Soliá</a></div>' },
  { image: 'assets/4-the emperor.webp', title: 'The Emperor', description: 'The Emperor represents leadership, discipline, and stability. This card embodies the power of a ruler who creates order and enforces rules, but it can also warn of tyranny, inflexibility, and potential abuse of power', song: '<iframe width="560" height="315" src="https://www.youtube.com/embed/FvMtMfIr-sU?si=XMzpO82PTfzzHPf8" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>' },
  { image: 'assets/8-strength.webp', title: 'Strength', description: 'The Strength represents inner courage, emotional and mental resilience, and the power of compassion and patience. It symbolizes confidence in the face of major challenges and proclaims the value of mental over physical strength', song: '<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1235151307&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/stoned_ranger" title="Yikesss" target="_blank" style="color: #cccccc; text-decoration: none;">Yikesss</a> · <a href="https://soundcloud.com/stoned_ranger/greatest-strength" title="Greatest Strength" target="_blank" style="color: #cccccc; text-decoration: none;">Greatest Strength</a></div>' },
  { image: 'assets/18-TheMoon.jpg', title: 'The Moon', description: 'The Moon represents the subconscious, mystery, and intuition. It symbolizes a journey through uncertainty, illusion, and emotional depth', song: '<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1913290439&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/pauljames37" title="Paul Cooper-James" target="_blank" style="color: #cccccc; text-decoration: none;">Paul Cooper-James</a> · <a href="https://soundcloud.com/pauljames37/delicate" title="Delicate" target="_blank" style="color: #cccccc; text-decoration: none;">Delicate</a></div>' },
  { image: 'assets/theHierophant.jpg', title: 'The Hierophant', description: 'he Hierophant represents traditional values, conformity, and adherence to established societal or spiritual norms. It symbolizes guidance, institutional beliefs, and the transmission of knowledge', song: '<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1564227238&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/rsun_music" title="rSUN" target="_blank" style="color: #cccccc; text-decoration: none;">rSUN</a> · <a href="https://soundcloud.com/rsun_music/rufus-du-sol-you-were-right-rsun-remix" title="RÜFÜS DU SOL - You Were Right (rSUN Remix)" target="_blank" style="color: #cccccc; text-decoration: none;">RÜFÜS DU SOL - You Were Right (rSUN Remix)</a></div>' },
  { image: 'assets/theHermit.jpg', title: 'The Hermit', description: 'The Hermit tarot card stands for introspection, solitude, and seeking inner wisdom. It represents a journey of self-discovery and contemplation', song: '<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/498034353&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/imyetep" title="yetep" target="_blank" style="color: #cccccc; text-decoration: none;">yetep</a> · <a href="https://soundcloud.com/imyetep/jai-wolf-lost-yetep-remix" title="Jai Wolf - Lost (Yetep Remix)" target="_blank" style="color: #cccccc; text-decoration: none;">Jai Wolf - Lost (Yetep Remix)</a></div>' },
  { image: 'assets/theSun.jpg', title: 'The Sun', description: 'The Sun is a very positive tarot card that represents joy, success, vitality, enlightenment, and clarity. It embodies optimism and positivity', song: '<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1887151845&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/nero" title="Nero" target="_blank" style="color: #cccccc; text-decoration: none;">Nero</a> · <a href="https://soundcloud.com/nero/solar" title="Solar" target="_blank" style="color: #cccccc; text-decoration: none;">Solar</a></div>' },
  { image: 'assets/6-theLovers.jpg', title: 'The Lovers', description: 'The Lovers represents love, harmony, and choices in relationships; it symbolizes strong connections and partnerships (usually romantic ones). It is also the symbol of mutual attraction. However', song: '<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/255958498&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/lana-del-rey" title="Lana Del Rey" target="_blank" style="color: #cccccc; text-decoration: none;">Lana Del Rey</a> · <a href="https://soundcloud.com/lana-del-rey/young-and-beautiful" title="Young And Beautiful" target="_blank" style="color: #cccccc; text-decoration: none;">Young And Beautiful</a></div>' },
  { image: 'assets/10-wheelOfFortune.jpg', title: 'Wheel of Fortune', description: 'The Wheel of Fortune symbolizes the cyclical nature of life; it highlights luck, change, and destiny. This card represents life’s inevitable ups and downs, opportunities, and turning points', song: '<iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/2gCQe48O4GMJz6oFBqnN9e?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>' },
  { image: 'assets/20-judgement.jpg', title: 'Judgment', description: 'The Judgment tarot card is a symbol of awakening. It represents a pivotal moment of realization and redemption and calls for self-reflection, rebirth, and transformation. Take it as a recommendation to reassess your past decisions', song: '<iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/58ge6dfP91o9oXMzq3XkIS?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>' },
  { image: 'assets/cups-ace.jpg', title: 'Ace of Cups', description: 'Ace of Cups represents issues of love, intimacy, deeper feelings, and compassion. It announces the new beginning of great possibility in this area of life. It can mark the start of a new relationship, or a deeper connection to an existing one', song: '<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1263180181&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/badbunny15" title="Bad-Bunny" target="_blank" style="color: #cccccc; text-decoration: none;">Bad-Bunny</a> · <a href="https://soundcloud.com/badbunny15/bad-bunny-moscow-mule" title="Moscow Mule" target="_blank" style="color: #cccccc; text-decoration: none;">Moscow Mule</a></div>' },
  { image: 'assets/cups-2.avif', title: 'Two of Cups', description: 'The Two of Cups symbolizes deep connections and partnerships, embodying unity, love, and mutual respect. It represents harmonious relationships and emotional balance', song: '<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/586740129&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/marshmellomusic" title="marshmello" target="_blank" style="color: #cccccc; text-decoration: none;">marshmello</a> · <a href="https://soundcloud.com/marshmellomusic/herewithme" title="Here With Me (ft. CHVRCHES)" target="_blank" style="color: #cccccc; text-decoration: none;">Here With Me (ft. CHVRCHES)</a></div>' },
  { image: 'assets/Cups-3.jpg', title: 'Three of Cups', description: 'The Three of Cups can signify parties, collaboration, and friendship. When this card appears in your Tarot reading you can look forward to a happy event in your life. It signifies a group of people coming together with open hearts and minds to celebrate important events. It is a very positive card that indicates happy times, uplifting and positive energy and good feelings', song: '<iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/3K7Q9PHUWPTaknlbFPThn2?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>' },
  { image: 'assets/Cups-4.jpg', title: 'Four of Cups', description: 'The Four of Cups signifies a need to reevaluate your current state of mind and perspective.You may be experiencing discontentment or restlessness. This card encourages you to open yourself up to new possibilities and opportunities. Reflect on your past, but don’t dwell on it', song: '<iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/3mq3tOTyvSqil4O8zUMHou?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>' },
  { image: 'assets/cups-5.jpg', title: 'Five of Cups', description: 'The Five of Cups symbolizes loss, regret, and focusing on what is gone. It reflects grief and disappointment but also points towards unacknowledged opportunities', song: '<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1912100621&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/user-910871239" title="michael lerm" target="_blank" style="color: #cccccc; text-decoration: none;">michael lerm</a> · <a href="https://soundcloud.com/user-910871239/sad-cinematic-piano-and-cello" title="Sad Cinematic Piano And Cello" target="_blank" style="color: #cccccc; text-decoration: none;">Sad Cinematic Piano And Cello</a></div>' },
  { image: 'assets/Cups-6.webp', title: 'Six of Cups', description: 'The Six of Cups symbolizes nostalgia, fond memories, and connections to the past, often reflecting a return to a more innocent time or a reunion', song: '<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/186940711&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/haidy-mohammed-1" title="Haidy.Emara" target="_blank" style="color: #cccccc; text-decoration: none;">Haidy.Emara</a> · <a href="https://soundcloud.com/haidy-mohammed-1/yanni-nostalgia-2" title="Yanni - Nostalgia" target="_blank" style="color: #cccccc; text-decoration: none;">Yanni - Nostalgia</a></div>' },
  { image: 'assets/Cups-7.jpg', title: 'Seven of Cups', description: 'The Seven of Cups symbolizes a multitude of choices and illusions, often leading to confusion and indecision. It represents daydreaming and wishful thinking', song: '<iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/3zBhihYUHBmGd2bcQIobrF?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>' },
  { image: 'assets/Cups-8.jpg', title: 'Eight of Cups', description: 'Eight of Cups suggests you sense that something is missing, particularly on an emotional or spiritual level, and instead of waiting around for things to get better, you know you need to leave that unfulfilling situation', song: '<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/336129232&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/urbans-music-school" title="Urbans Music School" target="_blank" style="color: #cccccc; text-decoration: none;">Urbans Music School</a> · <a href="https://soundcloud.com/urbans-music-school/otra-noche-en-miami-bad-bunny" title="BAD BUNNY - OTRA NOCHE EN MIAMI" target="_blank" style="color: #cccccc; text-decoration: none;">BAD BUNNY - OTRA NOCHE EN MIAMI</a></div>' },
  { image: 'assets/cups-9.avif', title: 'Nine of Cups', description: 'The Nine of Cups represents satisfaction, emotional fulfillment, and wishes coming true. It symbolizes contentment and enjoyment of lifes pleasures', song: '<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/272912234&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/blszrd" title="BLSZRD" target="_blank" style="color: #cccccc; text-decoration: none;">BLSZRD</a> · <a href="https://soundcloud.com/blszrd/alina-baraz-galimatias-fantasy-blszrd-remix" title="Alina Baraz &amp; Galimatias - Fantasy (BLSZRD Remix)" target="_blank" style="color: #cccccc; text-decoration: none;">Alina Baraz &amp; Galimatias - Fantasy (BLSZRD Remix)</a></div>' },
  { image: 'assets/Cups-10.webp', title: 'Ten of Cups', description: 'The Ten of Cups can represent the joys of a fulfilling life. It can also serve as a reminder that you are safe, secure, and loved', song: '<iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/7ujWf5dEnyWi6xuwIdfGoO?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>' },
  { image: 'assets/Cups-11-page.jpg', title: 'Page of Cups', description: 'The Page of Cups is asking you to explore your creative, emotional self. This card often appears when you are being called to trust your intuition and be open to the multitude of intuitive messages coming your way. Look for synchronicities and signs from nature that will guide you on your path. Be open to possibilities and ready to discover new aspects of yourself', song: '<iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/1h2xVEoJORqrg71HocgqXd?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>' },
  { image: 'assets/cups-12-Knight.jpg', title: 'Knight of Cups', description: 'The Knight of Cups represents romance, charm, and idealism, often embarking on emotional or creative quests. It symbolizes a graceful, artistic spirit', song: '<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/65638258&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/ichliebeklavier" title="IchLiebeKlavier" target="_blank" style="color: #cccccc; text-decoration: none;">IchLiebeKlavier</a> · <a href="https://soundcloud.com/ichliebeklavier/until-the-last-moment-yanni" title="&quot;Until the Last Moment - Yanni&quot; Piano Cover (w/ Song Background)" target="_blank" style="color: #cccccc; text-decoration: none;">&quot;Until the Last Moment - Yanni&quot; Piano Cover (w/ Song Background)</a></div>' },
  { image: 'assets/Cups-13-Queen.webp', title: 'Queen of Cups', description: 'The Queen of Cups symbolizes deep compassion, emotional security, and strong intuition. She represents nurturing, sensitivity, and psychic abilities', song: '<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1913999960&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/d-william-altig" title="The William Altig Choir" target="_blank" style="color: #cccccc; text-decoration: none;">The William Altig Choir</a> · <a href="https://soundcloud.com/d-william-altig/refuge-in-the-heart" title="Refuge In The Heart" target="_blank" style="color: #cccccc; text-decoration: none;">Refuge In The Heart</a></div>' },
  { image: 'assets/cups-14-king.jpg', title: 'King of Cups', description: 'The King of Cups represents emotional balance, wisdom, and compassion. He embodies a calm, diplomatic, and supportive nature', song: '<iframe style="border-radius:12px" src="https://open.spotify.com/embed/album/7sG2gH4SFp1GszxOkBZdZR?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>' },
  { image: 'assets/pentacles-ace.jpg', title: 'Ace of Pentacles', description: 'Ace of Pentacles represents new beginnings, opportunities, and the manifestation of abundance and prosperity. In its upright position, it signifies new financial or career opportunities, stability in relationships, and the potential to build wealth and success', song: '<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/768350050&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/badbunny15" title="Bad-Bunny" target="_blank" style="color: #cccccc; text-decoration: none;">Bad-Bunny</a> · <a href="https://soundcloud.com/badbunny15/bad-bunny-25-8" title="25/8" target="_blank" style="color: #cccccc; text-decoration: none;">25/8</a></div>' },
  { image: 'assets/pentacles-2.jpg', title: 'Two of Pentacles', description: 'The Two of Pentacles represents balancing multiple responsibilities, adaptability, and effective financial management. It symbolizes juggling different aspects of life with flexibility', song: '<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1285086586&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/lubalin" title="Lubalin" target="_blank" style="color: #cccccc; text-decoration: none;">Lubalin</a> · <a href="https://soundcloud.com/lubalin/what-if-its-not-enough" title="what if it&#x27;s not enough?" target="_blank" style="color: #cccccc; text-decoration: none;">what if it&#x27;s not enough?</a></div>' },
  { image: 'assets/pentacles-3.jpg', title: 'Three of Pentacles', description: 'he Three of Pentacles is traditionally the card of genius. This card symbolizes enterprise, success, and teamwork. See this card as an encouragement that you are on the right track. You are competent at what you do, and you are making progress', song: '<iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/3KliPMvk1EvFZu9cvkj8p1?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>' },
  { image: 'assets/pentacles-4.jpg', title: 'Four of Pentacles', description: 'You have everything you need to feel secure. Drawing the Four of Pentacles means you have built a solid foundation. Be careful not to become miserly and possessive over the things in your life', song: '<iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/22sLuJYcvZOSoLLRYev1s5?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>' },
  { image: 'assets/pentacles-5.jpg', title: 'Five of Pentacles', description: 'The Five of Pentacles symbolizes financial hardship, insecurity, and struggle, often indicating feelings of isolation and neglect', song: '<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1913130347&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/d-william-altig" title="The William Altig Choir" target="_blank" style="color: #cccccc; text-decoration: none;">The William Altig Choir</a> · <a href="https://soundcloud.com/d-william-altig/cry-for-the-poor-light-for-the-world" title="Cry For The Poor, Light For The World" target="_blank" style="color: #cccccc; text-decoration: none;">Cry For The Poor, Light For The World</a></div>' },
  { image: 'assets/pentacles-6.jpg', title: 'Six of Pentacles', description: 'The Six of Pentacles represents generosity, charity, and a fair distribution of resources. It symbolizes giving and receiving support with balance and fairness', song: '<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1517081029&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/approachingnirvana" title="approachingnirvana" target="_blank" style="color: #cccccc; text-decoration: none;">approachingnirvana</a> · <a href="https://soundcloud.com/approachingnirvana/in-the-shallows-free-love-tropics-2022-theme" title="In The Shallows (Free) | Love Tropics 2022 Theme" target="_blank" style="color: #cccccc; text-decoration: none;">In The Shallows (Free) | Love Tropics 2022 Theme</a></div>' },
  { image: 'assets/pentacles-7.jpg', title: 'Seven of Pentacles', description: 'The Seven of Pentacles symbolizes patience, long-term planning, and the fruits of hard work and investment. It represents perseverance and the anticipation of future rewards', song: '<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/255791497&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/marinadiamandis" title="MARINA" target="_blank" style="color: #cccccc; text-decoration: none;">MARINA</a> · <a href="https://soundcloud.com/marinadiamandis/forget-1" title="Forget" target="_blank" style="color: #cccccc; text-decoration: none;">Forget</a></div>' },
  { image: 'assets/pentacles-8.jpg', title: 'Eight of Pentacles', description: 'Eight of Pentacles symbolizes a period of labor, commitment, determination, and effort. Encouraging you to keep doing what you are doing as it will eventually lead to success', song: '<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/768009055&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/badbunny15" title="Bad-Bunny" target="_blank" style="color: #cccccc; text-decoration: none;">Bad-Bunny</a> · <a href="https://soundcloud.com/badbunny15/bad-bunny-myke-towers-estamos" title="Estamos Arriba" target="_blank" style="color: #cccccc; text-decoration: none;">Estamos Arriba</a></div>' },
  { image: 'assets/pentacles-9.webp', title: 'Nine of Pentacles', description: 'The Nine of Pentacles represents financial independence, luxury, and self-sufficiency. It symbolizes achievement, comfort, and prosperity', song: '<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/946210207&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/skelermusic" title="skeler." target="_blank" style="color: #cccccc; text-decoration: none;">skeler.</a> · <a href="https://soundcloud.com/skelermusic/danileigh-no-limits-skeler-remix" title="DaniLeigh - No Limits (Skeler Remix)" target="_blank" style="color: #cccccc; text-decoration: none;">DaniLeigh - No Limits (Skeler Remix)</a></div>' },
  { image: 'assets/pentacles-10.jpg', title: 'Ten of Pentacles', description: 'The Ten of Pentacles is a card that generally denotes stable foundations, security, and contentment in all facets of your life. Since it relates to matters of money or possessions, like all Pentacle cards, you may anticipate very prosperous times in those aspects of your life. This card deals with family and denotes obligations, values, and support. When it occurs in your Tarot reading, life should be calm and collected', song: '<iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/3aw9iWUQ3VrPQltgwvN9Xu?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>' },
  { image: 'assets/pentacles-11-page.jpg', title: 'Page of Pentacles', description: 'The Page of Pentacles symbolizes opportunity, studiousness, and practical ambition. It represents diligence, focus, and the pursuit of new beginnings', song: '<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/189503212&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/llendryon" title="Llendryon" target="_blank" style="color: #cccccc; text-decoration: none;">Llendryon</a> · <a href="https://soundcloud.com/llendryon/frederic-chopin-nocturne-in-c-sharp-minor-no-20-lento-con-gran-espressione" title="Frédéric Chopin - Nocturne in C sharp minor no. 20 &#x27;Lento con gran espressione&#x27; op. posth." target="_blank" style="color: #cccccc; text-decoration: none;">Frédéric Chopin - Nocturne in C sharp minor no. 20 &#x27;Lento con gran espressione&#x27; op. posth.</a></div>' },
  { image: 'assets/pentacles-12-Knight.jpg', title:'Knight of Pentacles', description: 'The Knight of Pentacles represents reliability, steadiness, and a methodical approach. It symbolizes hard work, practicality, and perseverance', song: '<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/226654312&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/yanni-music" title="Yanni Music" target="_blank" style="color: #cccccc; text-decoration: none;">Yanni Music</a> · <a href="https://soundcloud.com/yanni-music/santorini-live" title="Santorini - LIVE" target="_blank" style="color: #cccccc; text-decoration: none;">Santorini - LIVE</a></div>'},
  { image: 'assets/pentacles-queen.avif', title: 'Queen of Pentacles', description: 'The Queen of Pentacles symbolizes nurturing, practicality, and comfort. She represents financial stability, resourcefulness, and a down-to-earth nature', song: '<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1786580248&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/thisisdrove" title="Drove" target="_blank" style="color: #cccccc; text-decoration: none;">Drove</a> · <a href="https://soundcloud.com/thisisdrove/waterfall" title="Waterfall" target="_blank" style="color: #cccccc; text-decoration: none;">Waterfall</a></div>' },
  { image: 'assets/pentacles-14-king.jpg', title: 'King of Pentacles', description: 'The King of Pentacles represents wealth, business acumen, and stability. He symbolizes leadership, practicality, and success. ', song: '<iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/6ic8OlLUNEATToEFU3xmaH?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>' },
  { image: 'assets/wands-ace.jpg', title: 'Ace of Wands', description: 'Ace of wands represents the beginning of a journey, the birth of new ideas, and the initiation of creative projects. The hand emerging from the clouds in the card symbolizes the offer of new opportunities and the potential for growth', song: '<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/768349984&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/badbunny15" title="Bad-Bunny" target="_blank" style="color: #cccccc; text-decoration: none;">Bad-Bunny</a> · <a href="https://soundcloud.com/badbunny15/bad-bunny-la-dificil" title="La Difícil" target="_blank" style="color: #cccccc; text-decoration: none;">La Difícil</a></div>' },
  { image: 'assets/wands-2.webp', title: 'Two of Wands', description: 'The Two of Wands represents planning, decision-making, and future vision, often indicating discovery, direction, and exploration of potential choices', song: '<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1903710677&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/flomatik" title="Flomatik" target="_blank" style="color: #cccccc; text-decoration: none;">Flomatik</a> · <a href="https://soundcloud.com/flomatik/departure" title="Departure" target="_blank" style="color: #cccccc; text-decoration: none;">Departure</a></div>' },
  { image: 'assets/wands-3.jpg', title: 'Three of Wands', description: 'The Three of Wands coming upright means that you have planned your future, or are thinking of planning your future with more belief and conviction. This card indicates that you are happy with how things are going right now or that your plans are turning out to be fruitful. It also means that you are ready to take action and move forward with your plans. You are working to create a stable ground for your future', song: '<iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/2HHtWyy5CgaQbC7XSoOb0e?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>' },
  { image: 'assets/wands-4.jpg', title: 'Four of Wands', description: 'The Four of Wands represents celebration, harmony, and stability, often indicating community, happiness, and successful milestones', song: '<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/391900884&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/dayglowmusic" title="Dayglow" target="_blank" style="color: #cccccc; text-decoration: none;">Dayglow</a> · <a href="https://soundcloud.com/dayglowmusic/can-i-call-you-tonight" title="Can I Call You Tonight?" target="_blank" style="color: #cccccc; text-decoration: none;">Can I Call You Tonight?</a></div>' },
  { image: 'assets/wands-5.webp', title: 'Five of Wands', description: 'The Five of Wands represents conflict, competition, and struggle, often indicating tension, disagreements, and rivalry', song: '<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1817075754&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/aquariusmusic777" title="AquariusMusic" target="_blank" style="color: #cccccc; text-decoration: none;">AquariusMusic</a> · <a href="https://soundcloud.com/aquariusmusic777/hurricane" title="Hurricane" target="_blank" style="color: #cccccc; text-decoration: none;">Hurricane</a></div>' },
  { image: 'assets/wands-6.webp', title: 'Six of Wands', description: 'The Six of Wands represents victory, success, and recognition, often indicating achievement, confidence, and acclaim', song: '<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/665619392&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/user8585647" title="Two Steps From Hell" target="_blank" style="color: #cccccc; text-decoration: none;">Two Steps From Hell</a> · <a href="https://soundcloud.com/user8585647/victory" title="Victory" target="_blank" style="color: #cccccc; text-decoration: none;">Victory</a></div>' },
  { image: 'assets/wands-7.jpg', title: 'Seven of Wands', description: 'The Seven of Wands represents defense, resilience, and determination, often indicating standing your ground, facing challenges, and perseverance', song: '<iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/4djnw5Fd9KSs718VXHXfmL?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>' },
  { image: 'assets/wands-8.jpg', title: 'Eight of Wands', description: 'Eight of Wands holds a powerful message of swift action, rapid progression, and forward momentum. It urges us to seize opportunities and anticipate swift outcomes. Like rockets soaring through the sky, our desires are quickly moving from the realm of imagination to the realm of tangible existence', song: '<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/768215869&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/badbunny15" title="Bad-Bunny" target="_blank" style="color: #cccccc; text-decoration: none;">Bad-Bunny</a> · <a href="https://soundcloud.com/badbunny15/bad-bunny-tainy-callaita" title="Callaita" target="_blank" style="color: #cccccc; text-decoration: none;">Callaita</a></div>' },
  { image: 'assets/wands-9.avif', title: 'Nine of Wands', description: 'The Nine of Wands represents persistence, resilience, and endurance, often indicating caution, a last stand, and setting boundaries', song: '<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/490096386&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/ekalimusic" title="EKALI" target="_blank" style="color: #cccccc; text-decoration: none;">EKALI</a> · <a href="https://soundcloud.com/ekalimusic/leaving-ft-yuna" title="Leaving ft. Yuna" target="_blank" style="color: #cccccc; text-decoration: none;">Leaving ft. Yuna</a></div>' },
  { image: 'assets/wands-10.jpg', title: 'Ten of Wands', description: 'The Ten of Wands in the upright position indicates that you have been already struggling because of responsibilities, but now you have taken on more responsibilities, and a heavier workload which will be a lot of burdens for you to handle. This hard work is not permanent and you are almost at the finish line. You are gathering all your strength and resources and putting in all the hard work that is required so that soon you will get to enjoy the fruit of your success. With this card, you have to do whatever it takes to get to completion -- nothing can be allowed to interfere', song: '<iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/2k4FNm30FYR4VqatIAzGGN?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>' },
  { image: 'assets/wands-11-page.jpg', title: 'Page of Wands', description: 'The Page of Wands represents enthusiasm, adventure, and exploration, often indicating a free spirit, creativity, and confidence', song: '<iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/37zuIvk4KBkAxxLJsxJaHq?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>' },
  { image: 'assets/wands-12-Knight.webp', title: 'Knight of Wands', description: 'The Knight of Wands represents energy, passion, and adventurousness, often indicating confidence, action-orientation, and charisma', song: '<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1914130508&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/ian-haddock-2" title="Ian Haddock" target="_blank" style="color: #cccccc; text-decoration: none;">Ian Haddock</a> · <a href="https://soundcloud.com/ian-haddock-2/synergy-midnight-tokyo-radio-remix" title="Synergy - Midnight Tokyo Radio remix" target="_blank" style="color: #cccccc; text-decoration: none;">Synergy - Midnight Tokyo Radio remix</a></div>' },
  { image: 'assets/wands-13-queen.jpg', title: 'Queen of Wands', description: 'The Queen of Wands represents charisma, confidence, and independence, often indicating passion, determination, warmth, and vibrancy', song: '<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/564551526&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/amalaofficial" title="DOJA CAT" target="_blank" style="color: #cccccc; text-decoration: none;">DOJA CAT</a> · <a href="https://soundcloud.com/amalaofficial/tia-tamera-feat-rico-nasty" title="Tia Tamera (feat. Rico Nasty)" target="_blank" style="color: #cccccc; text-decoration: none;">Tia Tamera (feat. Rico Nasty)</a></div>' },
  { image: 'assets/wands-14-king.jpg', title: 'King of Wands', description: 'The King of Wands represents leadership, vision, and entrepreneurship; it is often interpreted as a symbol of courage, ambition, and charisma', song: '<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/341396245&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/barnscourtney" title="Barns Courtney" target="_blank" style="color: #cccccc; text-decoration: none;">Barns Courtney</a> · <a href="https://soundcloud.com/barnscourtney/champion" title="Champion" target="_blank" style="color: #cccccc; text-decoration: none;">Champion</a></div>' },
  { image: 'assets/swords-ace.jpg', title: 'Ace of Swords', description: 'Ace of Swords represents breakthroughs, new ideas, mental clarity, and success. It is a symbol of triumph and victory, but also reminds us that the path to success may be challenging', song: '<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/768349999&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/badbunny15" title="Bad-Bunny" target="_blank" style="color: #cccccc; text-decoration: none;">Bad-Bunny</a> · <a href="https://soundcloud.com/badbunny15/bad-bunny-si-veo-a-tu-mama" title="Si Veo a Tu Mamá" target="_blank" style="color: #cccccc; text-decoration: none;">Si Veo a Tu Mamá</a></div>' },
  { image: 'assets/swords-2.webp', title: 'Two of Swords', description: 'The Two of Swords symbolizes indecision, balance, and stalemate. It represents a need for resolution in the face of conflict and uncertainty', song: '<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/905247559&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/itscopycatt" title="COPYCATT" target="_blank" style="color: #cccccc; text-decoration: none;">COPYCATT</a> · <a href="https://soundcloud.com/itscopycatt/rushing-back" title="Rushing Back (COPYCATT Remix)" target="_blank" style="color: #cccccc; text-decoration: none;">Rushing Back (COPYCATT Remix)</a></div>' },
  { image: 'assets/swords-3.jpg', title: 'Three of Swords', description: 'One message this card brings is to cut some things loose. In spite of sentimental memories and emotional attachments, we need to let go of relationships that either cannot live up to their promise or have outlived the pleasure and support we once found in them. It might be healthier to disentangle yourself and start fresh', song: '<iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/51mxzPTcTaHYI5D7tls7d7?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>' },
  { image: 'assets/swords-4.jpg', title: 'Four of Swords', description: 'A Four in this suit sends a message to take some time out, surrendering worldly concerns and retreating to a sheltered place of serenity away from the hustle and bustle. The oldest Tarot card images suggest a visit to the tombs of our ancestors, a place to contemplate your mortality and breathe in the dust of those who brought you here', song: '<iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/0lJrPatloYarTbsKciShJu?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>' },
  { image: 'assets/swords-5.jpg', title: 'Five of Swords', description: 'The Five of Swords represents conflict, defeat, and unethical victory, often signifying tension, aggression, and hostility', song: '<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1899496206&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/urunc" title="Urunc" target="_blank" style="color: #cccccc; text-decoration: none;">Urunc</a> · <a href="https://soundcloud.com/urunc/born-again" title="Born Again" target="_blank" style="color: #cccccc; text-decoration: none;">Born Again</a></div>' },
  { image: 'assets/swords-6.jpg', title: 'Six of Swords', description: 'The Six of Swords represents a period of transition, moving on, and embarking on a healing journey. It symbolizes change, recovery, and release', song: '<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/934673413&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/relaxing-music-production" title="RELAXING MUSIC 😊 (Piano - Sleep - Study - Yoga)" target="_blank" style="color: #cccccc; text-decoration: none;">RELAXING MUSIC 😊 (Piano - Sleep - Study - Yoga)</a> · <a href="https://soundcloud.com/relaxing-music-production/tranquility-part-24mp3" title="Minimalism No. 4, Lago di Lugano - Raphaël Novarina [Piano]" target="_blank" style="color: #cccccc; text-decoration: none;">Minimalism No. 4, Lago di Lugano - Raphaël Novarina [Piano]</a></div>' },
  { image: 'assets/swords-7.jpg', title: 'Seven of Swords', description: 'The Seven of Swords symbolizes deception, strategy, and sneakiness, often indicating caution, tactics, and secrecy', song: '<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/257083512&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/talkingheads" title="Talking Heads" target="_blank" style="color: #cccccc; text-decoration: none;">Talking Heads</a> · <a href="https://soundcloud.com/talkingheads/psycho-killer" title="Psycho Killer" target="_blank" style="color: #cccccc; text-decoration: none;">Psycho Killer</a></div>' },
  { image: 'assets/swords-8.jpg', title: 'Eight of Swords', description: 'Eight of Swords signifies a feeling of being trapped, restricted, and backed into a corner. It represents negative thoughts, self-imposed limitations, and a victim mentality. You may find yourself imprisoned by your own beliefs and unable to see the possibilities for change', song: 'https://soundcloud.com/badbunny15/bad-bunny-solo-de-mi?utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing' },
  { image: 'assets/swords-9.jpg', title: 'Nine of Swords', description: 'The Nine of Swords symbolizes anxiety, worry, fear, and mental torment, often indicating overwhelming thoughts and guilt', song: '<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1065012607&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/skrillex" title="Skrillex" target="_blank" style="color: #cccccc; text-decoration: none;">Skrillex</a> · <a href="https://soundcloud.com/skrillex/supersonic-my-existence" title="Skrillex, Noisia, josh pan &amp; Dylan Brady - Supersonic (My Existence)" target="_blank" style="color: #cccccc; text-decoration: none;">Skrillex, Noisia, josh pan &amp; Dylan Brady - Supersonic (My Existence)</a></div>' },
  { image: 'assets/swords-10.jpg', title: 'Ten of Swords', description: 'The Ten of this suit represents finality, the end of something. As is easy to grasp from the picture in many decks, there is no hope for revival here. A limit has been reached, a line has been crossed and there is no turning back. The waiting and wondering are over. There is no more ambiguity. You can rightly let go and move on, as there is no more progress to be made here', song: '<iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/5YqltLsjdqFtvqE7Nrysvs?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>' },
  { image: 'assets/swords-11-page.jpg', title: 'Page of Swords', description: 'The Page of Swords represents curiosity, mental agility, and vigilance, often indicating tactfulness, communication, and explorative thinking', song: '<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1172343979&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/wazmusic" title="DVRST" target="_blank" style="color: #cccccc; text-decoration: none;">DVRST</a> · <a href="https://soundcloud.com/wazmusic/autumn-wind" title="Autumn Wind" target="_blank" style="color: #cccccc; text-decoration: none;">Autumn Wind</a></div>' },
  { image: 'assets/swords-12-knight.jpg', title: 'Knight of Swords', description: 'The Knight of Swords represents action, ambition, and assertiveness, often indicating speed, directness, and determination', song: '<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1630170483&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/apathy-582313353" title="Apathy" target="_blank" style="color: #cccccc; text-decoration: none;">Apathy</a> · <a href="https://soundcloud.com/apathy-582313353/angel_a-royalty-background-music-free-download" title="Angel_A royalty background music (FREE DOWNLOAD)" target="_blank" style="color: #cccccc; text-decoration: none;">Angel_A royalty background music (FREE DOWNLOAD)</a></div>' },
  { image: 'assets/swords-13-queen.jpg', title: 'Queen of Swords', description: 'Queen of Swords represents intellect, wisdom, and clear judgment. Whether appearing upright or reversed, this card prompts us to embrace our intellectual prowess, set boundaries, and communicate effectively', song: '<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1639720773&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/badbunny15" title="Bad-Bunny" target="_blank" style="color: #cccccc; text-decoration: none;">Bad-Bunny</a> · <a href="https://soundcloud.com/badbunny15/bad-bunny-nadie-sabe" title="NADIE SABE" target="_blank" style="color: #cccccc; text-decoration: none;">NADIE SABE</a></div>' },
  { image: 'assets/swords-14-king.jpg', title: 'King of Swords', description: 'The King of Swords symbolizes authority, rationality, and fairness, often indicating intellectual power, analytical thinking, and ethical judgment', song: '<iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/5muxYe1JxKQ9BmxnXRTaGx?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>' },
  ];

const spread = localStorage.getItem('readingType') || '1'; // Default to '1' if not set for testing
const userInput = localStorage.getItem('issueText');

const dailySpread = document.getElementById('daily-spread');
const dailyCard = document.getElementById('daily-card');

const pastPresentFutureSpread = document.getElementById('pastPresentFuture-spread');
const pastCard = document.getElementById('past-card');
const presentCard = document.getElementById('present-card');
const futureCard = document.getElementById('future-card');

const issueSpread = document.getElementById('specificIssue-spread');
const clarityCard1 = document.getElementById('clarity-card1');
const clarityCard2 = document.getElementById('clarity-card2');
const clarityCard3 = document.getElementById('clarity-card3');

// Draw cards based on the spread selection
function drawCards() {
  let cards = [];
  if (spread === '1') {
      cards.push(getRandomCard());
  } else if (spread === '2') {
      cards.push(getRandomCard(), getRandomCard(), getRandomCard());
  } else if (spread === '3') {
      cards.push(getRandomCard(), getRandomCard(), getRandomCard());
  }

  // saveCardHistory(cards);
  displayCards(spread, cards);
}

// Call drawCards when the page loads
document.addEventListener('DOMContentLoaded', drawCards);

// Draw random Card
function getRandomCard() {
  let index = Math.floor(Math.random() * tarotCards.length);
  return tarotCards[index];
};

// Display the drawn cards based on the selected spread
function displayCards(spread, cards) {
  // Hide all sections
  dailySpread.classList.add('d-none');
  pastPresentFutureSpread.classList.add('d-none');
  issueSpread.classList.add('d-none');

  if (spread === '1') {
      updateCard(document.getElementById('daily-card'), cards[0]);
      dailySpread.classList.remove('d-none');

  } else if (spread === '2') {
      updateCard(document.getElementById('past-card'), cards[0]);
      updateCard(document.getElementById('present-card'), cards[1]);
      updateCard(document.getElementById('future-card'), cards[2]);
      pastPresentFutureSpread.classList.remove('d-none');

  } else if (spread === '3') {
      updateCard(document.getElementById('clarity-card1'), cards[0]);
      updateCard(document.getElementById('clarity-card2'), cards[1]);
      updateCard(document.getElementById('clarity-card3'), cards[2]);
      issueSpread.classList.remove('d-none');
  }
};

// Update a card's image, description, and song
// cardElement represents the <div> with the image, description and songs.
function updateCard(cardElement, card) {
  cardElement.querySelector('h4').textContent = card.title;
  cardElement.querySelector('img').src = card.image;
  cardElement.querySelector('p').textContent = card.description;
  cardElement.querySelector('#song').innerHTML = card.song;
  document.getElementById('userInput').textContent = userInput;
}

// Redirect home when draw again is selected

const redirectPage = function (url) {
  redirectURL = url;
  location.assign(url);
};

const buttons = document.querySelectorAll("button");

buttons.forEach(btn => {
  btn.addEventListener('click', function (event) {
    event.preventDefault();
    redirectPage('./index.html');
  });
});

// Not currently in use - Store card selection history in localStorage
function saveCardHistory(cards) {
  let history = JSON.parse(localStorage.getItem('cardHistory')) || [];
  history.push({ date: new Date(), cards });
  localStorage.setItem('cardHistory', JSON.stringify(history));
};